name: vec
description: Additional List extensions and a zero cost Vec (vector) type.
version: 0.3.0
repository: https://github.com/mcmah309/vec

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust_core: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
