name: vec
description: A zero cost growable vector type
version: 0.2.0
repository: https://github.com/mcmah309/vec

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust_core: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
